import type { FastifyInstance } from 'fastify';
import type { Prisma } from '@prisma/client';
import { prisma } from '../db.js';
import { CreateCharacterSchema } from '@lcos/shared';
import {
  generateCharacter,
  generateCharacterWithSeed,
  rerollCharacter,
  generateLCOSCharacter,
  deriveHexagramReading,
  getSubtasteDesignation,
  generateOroCulturalName,
  listOroCultures,
  type OroCultureId,
  type OroMode,
  type OroForm,
  type OroGender,
  type OroArchetype,
} from '@lcos/oripheon';

export async function characterRoutes(fastify: FastifyInstance): Promise<void> {
  // POST /characters - Create a new character
  fastify.post('/characters', async (request, reply) => {
    try {
      const body = CreateCharacterSchema.parse(request.body);

      const character = await prisma.character.create({
        data: body as any,
      });

      return reply.code(201).send(character);
    } catch (error) {
      if (error instanceof Error && error.name === 'ZodError') {
        return reply.code(400).send({ error: 'Validation error', details: error });
      }
      throw error;
    }
  });

  // GET /characters - List all characters
  fastify.get('/characters', async (_request, reply) => {
    const characters = await prisma.character.findMany({
      orderBy: { createdAt: 'desc' },
      include: { position: true },
    });

    return reply.send(characters);
  });

  // GET /characters/:id - Get a character by ID
  fastify.get<{ Params: { id: string } }>('/characters/:id', async (request, reply) => {
    const { id } = request.params;

    const character = await prisma.character.findUnique({
      where: { id },
      include: { position: true },
    });

    if (!character) {
      return reply.code(404).send({ error: 'Character not found' });
    }

    return reply.send(character);
  });

  // PATCH /characters/:id - Update a character
  fastify.patch<{ Params: { id: string } }>('/characters/:id', async (request, reply) => {
    const { id } = request.params;
    const body = request.body as {
      name?: string;
      bio?: string;
      avatarUrl?: string;
      avatarPosition?: string;
      aliases?: string[];
      personaTags?: string[];
      toneAllowed?: string[];
      toneForbidden?: string[];
      systemPrompt?: string;
      currentArc?: string | null;
      timelineState?: Record<string, unknown>;
    };

    const character = await prisma.character.findUnique({
      where: { id },
    });

    if (!character) {
      return reply.code(404).send({ error: 'Character not found' });
    }

    const { timelineState, ...rest } = body;
    const updated = await prisma.character.update({
      where: { id },
      data: {
        ...rest,
        ...(timelineState !== undefined && {
          timelineState: timelineState as Prisma.InputJsonValue,
        }),
      },
    });

    return reply.send(updated);
  });

  // DELETE /characters/:id - Delete a character
  fastify.delete<{ Params: { id: string } }>('/characters/:id', async (request, reply) => {
    const { id } = request.params;

    const character = await prisma.character.findUnique({
      where: { id },
    });

    if (!character) {
      return reply.code(404).send({ error: 'Character not found' });
    }

    // Delete associated content items first
    await prisma.contentItem.deleteMany({
      where: { characterId: id },
    });

    // Delete the character
    await prisma.character.delete({
      where: { id },
    });

    return reply.code(204).send();
  });

  // POST /characters/generate - Generate a random character using LCOS Oripheon
  fastify.post('/characters/generate', async (request, reply) => {
    const body = request.body as {
      seed?: number;
      heritage?: string;
      gender?: string;
      blendHeritage?: boolean;
      mononym?: boolean;
      mononymType?: 'squishe' | 'simple' | 'aminal-blend' | 'aminal-clear';
      relic?: boolean;
      relicEra?: 'archaic' | 'modern';
      lockedRelic?: { object: string; category: string; origin: string };
      core?: string;
      variance?: number;
      // Cultural mode: when true, the name is generated by the
      // diasporic / decolonial engine (@violet-sphinx/names) and
      // overrides the heritage-pool name. Bóveda still owns
      // backstory + arcana + relics; only the name surface changes.
      cultural?: boolean;
      culturalCultures?: string[];
      culturalMode?: 'real' | 'fictional' | 'mythic' | 'archetype' | 'internet';
      culturalForm?: 'mononym' | 'first' | 'surname' | 'first_surname' | 'full_with_epithet';
      culturalGender?: 'm' | 'f' | 'a';
      culturalArchetype?: string;
      culturalOrnament?: 0 | 0.5 | 1;
      culturalWithTitle?: boolean;
      culturalSurnameRegister?: 'auto' | 'colonial' | 'reclaimed' | 'compound';
      culturalSurnameCulture?: string;
    } | undefined;

    // Use the extended LCOS generator with multiple archetype systems
    const generated = generateLCOSCharacter({
      seed: body?.seed,
      heritage: body?.heritage,
      gender: body?.gender,
      blendHeritage: body?.blendHeritage,
      mononym: body?.mononym,
      mononymType: body?.mononymType,
      relic: body?.relic,
      relicEra: body?.relicEra,
      lockedRelic: body?.lockedRelic as any,
      core: body?.core as any,
      variance: body?.variance,
    });

    // Cultural override: replace the name with the Òrò engine's output
    // and attach cultural metadata. Backstory, arcana, personality,
    // appearance, relics still come from Bóveda's engine — that
    // division is the merger pattern (Òrò = name + lineage,
    // Bóveda = lore + relic + persona).
    if (body?.cultural) {
      const oro = generateOroCulturalName({
        cultures: body.culturalCultures as OroCultureId[] | undefined,
        mode: body.culturalMode as OroMode | undefined,
        form: body.culturalForm as OroForm | undefined,
        gender: body.culturalGender as OroGender | undefined,
        archetype: body.culturalArchetype as OroArchetype | undefined,
        ornament: body.culturalOrnament,
        withTitle: body.culturalWithTitle,
        surnameRegister: body.culturalSurnameRegister,
        surnameCulture: body.culturalSurnameCulture as OroCultureId | undefined,
      });
      if (oro) {
        generated.name = oro.fullName;
        const enriched = generated as unknown as Record<string, unknown>;
        enriched.cultural = {
          cultureId: oro.raw.cultureId,
          region: oro.raw.region,
          era: oro.raw.era,
          source: oro.raw.source,
          sacred: oro.raw.sacred,
          lineage: oro.raw.lineage,
          rationale: oro.raw.rationale,
        };
      }
    }

    return reply.send(generated);
  });

  // GET /characters/oro-cultures - List cultures available in the
  // diasporic naming engine. Used by the studio picker.
  fastify.get('/characters/oro-cultures', async (_request, reply) => {
    return reply.send({ cultures: listOroCultures() });
  });

  // POST /characters/names - Names-only surface: returns a batch of
  // generated names without creating characters. Used by the /names
  // exploration page in the studio (the Òrò surface absorbed into
  // Bóveda).
  fastify.post('/characters/names', async (request, reply) => {
    const body = request.body as {
      cultures?: string[];
      mode?: 'real' | 'fictional' | 'mythic' | 'archetype' | 'internet';
      form?: 'mononym' | 'first' | 'surname' | 'first_surname' | 'full_with_epithet';
      gender?: 'm' | 'f' | 'a';
      archetype?: string;
      ornament?: 0 | 0.5 | 1;
      withTitle?: boolean;
      surnameRegister?: 'auto' | 'colonial' | 'reclaimed' | 'compound';
      surnameCulture?: string;
      count?: number;
    } | undefined;
    const { generateOroBatch } = await import('@lcos/oripheon');
    const results = generateOroBatch({
      cultures: body?.cultures as OroCultureId[] | undefined,
      mode: body?.mode as OroMode | undefined,
      form: body?.form as OroForm | undefined,
      gender: body?.gender as OroGender | undefined,
      archetype: body?.archetype as OroArchetype | undefined,
      ornament: body?.ornament,
      withTitle: body?.withTitle,
      surnameRegister: body?.surnameRegister,
      surnameCulture: body?.surnameCulture as OroCultureId | undefined,
      count: body?.count,
    });
    return reply.send({ names: results });
  });

  // GET /characters/oro-lineages - Cross-culture name lineage threads
  // (Ogun → Ogou → Ogún, Kwasi → Quashie, etc.). Powers the /names/lineage
  // page in the studio.
  fastify.get('/characters/oro-lineages', async (_request, reply) => {
    const { LINEAGES } = await import('@violet-sphinx/names');
    return reply.send({ lineages: LINEAGES });
  });

  // POST /characters/from-persona - Create a Bóveda character from a
  // Tizita persona. Idempotent: if a character already exists in
  // Bóveda bound to the same persona, return that instead. The
  // tizitaPersonaId field on Character is the persistent link, so
  // photo-library lookups and avatar fetches keep working.
  fastify.post('/characters/from-persona', async (request, reply) => {
    const body = request.body as {
      personaId?: string;
      nameOverride?: string;
      worldId?: string;
    } | undefined;
    if (!body?.personaId?.trim()) {
      return reply.code(400).send({ error: 'personaId is required' });
    }

    // Idempotence
    const existing = await prisma.character.findFirst({
      where: { tizitaPersonaId: body.personaId },
    });
    if (existing) {
      return reply.send({
        id: existing.id,
        character: existing,
        created: false,
        reused: true,
      });
    }

    // Optionally fetch persona details from Tizita
    const TIZITA_API_URL = (process.env.TIZITA_API_URL || 'http://localhost:8001/api/v1').replace(/\/$/, '');
    let displayName: string | null = null;
    let photoCount = 0;
    let tizitaReachable = false;
    try {
      const res = await fetch(`${TIZITA_API_URL}/personas/${body.personaId}`, {
        signal: AbortSignal.timeout(5000),
      });
      if (res.ok) {
        const persona = await res.json() as { display_name?: string | null; photo_count?: number };
        displayName = persona.display_name?.trim() ?? null;
        photoCount = persona.photo_count ?? 0;
        tizitaReachable = true;
      } else if (res.status === 404) {
        return reply.code(404).send({ error: `persona ${body.personaId} not found in Tizita` });
      }
    } catch {
      // Tizita unreachable; we can still proceed with nameOverride
    }

    const inferredName =
      body.nameOverride?.trim() ||
      displayName ||
      (tizitaReachable ? `Unnamed · ${body.personaId.slice(0, 8)}` : null);
    if (!inferredName) {
      return reply.code(503).send({
        error: 'Tizita is unreachable and no nameOverride was provided. Start Tizita on :8001 or pass nameOverride in the body.',
      });
    }

    const today = new Date().toISOString().split('T')[0];
    const bioStub = tizitaReachable
      ? `Stubbed from Tizita persona ${body.personaId} on ${today}.${photoCount ? ` ${photoCount} photo${photoCount === 1 ? '' : 's'} on file.` : ''}`
      : `Stubbed from Tizita persona ${body.personaId} on ${today}.`;

    const character = await prisma.character.create({
      data: {
        name: inferredName,
        bio: bioStub,
        tizitaPersonaId: body.personaId,
        source: 'PERSONA',
        ...(body.worldId ? { worldId: body.worldId } : {}),
      },
    });

    return reply.send({
      id: character.id,
      character,
      created: true,
      reused: false,
      persona: tizitaReachable
        ? { id: body.personaId, display_name: displayName, photo_count: photoCount }
        : null,
    });
  });

  // POST /characters/:id/loras - Attach a LoRA to a character. The
  // LoRA file lives elsewhere (Tizita / S3 / shared storage); this
  // attaches its identifier + metadata to the character so image-gen
  // surfaces (Genoma, ComfyUI, thumbnail compositor) can pick the
  // right adapter when rendering.
  fastify.post<{ Params: { id: string } }>('/characters/:id/loras', async (request, reply) => {
    const lora = request.body as {
      id: string;            // LoRA identifier (Tizita ref, civitai id, etc.)
      name?: string;         // Display name (e.g. "Ubani v3")
      source?: string;       // "tizita" | "civitai" | "local" | "starforge"
      trigger?: string;      // The trigger word(s) that activate it
      weight?: number;       // Default weight, 0.0-1.0
      baseModel?: string;    // "sdxl" | "sd15" | "flux" | etc.
      trainedFromPersonaId?: string; // Tizita persona this was trained from
      thumbnailUrl?: string;
      metadata?: Record<string, unknown>;
    };
    if (!lora?.id) return reply.code(400).send({ error: 'lora.id is required' });

    const char = await prisma.character.findUnique({ where: { id: request.params.id } });
    if (!char) return reply.code(404).send({ error: 'character not found' });

    const existing = Array.isArray(char.loras) ? (char.loras as unknown[]) : [];
    const filtered = existing.filter((x) => (x as { id?: string })?.id !== lora.id);
    const next = [...filtered, lora];

    const updated = await prisma.character.update({
      where: { id: request.params.id },
      data: { loras: next as never },
    });
    return reply.send({ id: updated.id, loras: updated.loras });
  });

  // DELETE /characters/:id/loras/:loraId - Detach a LoRA from a character.
  fastify.delete<{ Params: { id: string; loraId: string } }>(
    '/characters/:id/loras/:loraId',
    async (request, reply) => {
      const char = await prisma.character.findUnique({ where: { id: request.params.id } });
      if (!char) return reply.code(404).send({ error: 'character not found' });
      const existing = Array.isArray(char.loras) ? (char.loras as unknown[]) : [];
      const next = existing.filter((x) => (x as { id?: string })?.id !== request.params.loraId);
      const updated = await prisma.character.update({
        where: { id: request.params.id },
        data: { loras: next as never },
      });
      return reply.send({ id: updated.id, loras: updated.loras });
    }
  );

  // POST /characters/generate/:seed - Generate a character with specific seed
  fastify.post<{ Params: { seed: string } }>('/characters/generate/:seed', async (request, reply) => {
    const seed = parseInt(request.params.seed, 10);

    if (isNaN(seed)) {
      return reply.code(400).send({ error: 'Invalid seed - must be a number' });
    }

    const generated = generateCharacterWithSeed(seed);
    return reply.send(generated);
  });

  // POST /characters/reroll/:seed - Reroll a character with optional overrides
  fastify.post<{ Params: { seed: string } }>('/characters/reroll/:seed', async (request, reply) => {
    const seed = parseInt(request.params.seed, 10);

    if (isNaN(seed)) {
      return reply.code(400).send({ error: 'Invalid seed - must be a number' });
    }

    const body = request.body as { heritage?: string; gender?: string } | undefined;
    const generated = rerollCharacter(seed, {
      heritage: body?.heritage as any,
      gender: body?.gender as any,
    });

    return reply.send(generated);
  });

  // Helper: sync oripheon data for a single character record.
  // Returns { updated, status } where status indicates what happened.
  // NEVER overwrites existing hexagram, subtaste, or core generated data.
  async function syncOripheonForCharacter(character: { id: string; name: string; bio: string | null; timelineState: any }) {
    const ts = (character.timelineState as Record<string, any>) || {};
    const oripheon = ts.oripheon || {};
    const generated = oripheon.generated;

    const hasAxes = !!generated?.personality?.axes;
    const hasArcana = !!generated?.arcana;
    const hasHexagram = !!generated?.hexagram;
    const hasSubtaste = !!generated?.subtaste;

    // Fully complete — nothing to do
    if (hasAxes && hasArcana && hasHexagram && hasSubtaste) {
      return { updated: null, status: 'already_complete' as const };
    }

    let updatedGenerated: any;
    let extraUpdates: Record<string, any> = {};

    if (hasAxes && hasArcana) {
      // Core data present — only fill in missing derived fields, preserve everything else
      updatedGenerated = { ...generated };
      if (!hasHexagram) {
        updatedGenerated.hexagram = deriveHexagramReading(generated.personality.axes);
      }
      if (!hasSubtaste) {
        updatedGenerated.subtaste = getSubtasteDesignation('tarot', generated.arcana.archetype);
      }
    } else {
      // No core data — full generation needed
      const fresh = generateLCOSCharacter();
      updatedGenerated = fresh;
      extraUpdates = {
        bio: fresh.backstory?.substring(0, 500) || character.bio,
      };
    }

    const updated = await prisma.character.update({
      where: { id: character.id },
      data: {
        ...extraUpdates,
        timelineState: {
          ...ts,
          oripheon: {
            ...oripheon,
            seed: oripheon.seed || updatedGenerated.seed,
            generated: updatedGenerated,
            subtaste: updatedGenerated.subtaste,
          },
        },
      },
    });

    const status = (hasAxes && hasArcana) ? 'enriched' as const : 'generated' as const;
    return { updated, status };
  }

  // POST /characters/:id/sync-oripheon - Sync/generate oripheon data for a character
  fastify.post<{ Params: { id: string } }>('/characters/:id/sync-oripheon', async (request, reply) => {
    const { id } = request.params;
    const character = await prisma.character.findUnique({ where: { id } });
    if (!character) return reply.code(404).send({ error: 'Character not found' });

    const { updated, status } = await syncOripheonForCharacter(character);

    if (status === 'already_complete') {
      return reply.send(character);
    }

    return reply.send(updated);
  });

  // POST /characters/sync-oripheon-all - Sync oripheon data for all characters
  fastify.post('/characters/sync-oripheon-all', async (_request, reply) => {
    const characters = await prisma.character.findMany();
    const results = [];

    for (const character of characters) {
      const { status } = await syncOripheonForCharacter(character);
      results.push({ id: character.id, name: character.name, status });
    }

    return reply.send({ synced: results.length, results });
  });
}
