/**
 * Strip em dashes (and en dashes used as em dashes) from any
 * generated text. Standing rule: never ship em dashes regardless
 * of how strongly the LLM wants them.
 *
 * Replacement strategy:
 *   - " — " (with surrounding spaces, used as a clause break)
 *     becomes ". " (sentence break, capitalising next char)
 *   - "—" (no spaces, used as a clause join inside a phrase)
 *     becomes ", "
 *   - " – " and "–" treated identically (some models sub en for em)
 *
 * Also collapses ".  ." artefacts that can result from the swap.
 */

export function stripEmDashes(input: string): string {
  if (typeof input !== 'string' || input.length === 0) return input;
  let out = input;

  // Spaced variants first (most common, model-output shape).
  out = out.replace(/\s+[—–]\s+/g, '. ');
  // Unspaced.
  out = out.replace(/[—–]/g, ', ');
  // Capitalise after sentence break (only if the next char is a-z).
  out = out.replace(/\.\s+([a-z])/g, (_m, c) => `. ${c.toUpperCase()}`);
  // Collapse stray double periods.
  out = out.replace(/\.\s*\./g, '.');
  // Collapse ", ," doubles from clause-join replacement.
  out = out.replace(/,\s*,/g, ',');

  return out;
}

/**
 * Strip system / platform names that leak from the system prompt
 * into character output. Characters are not meta-aware: they do not
 * name Bóveda, the cube, the bóveda altar, the threshold, the vault,
 * or any platform-level vocabulary.
 *
 * Replaces inline references with neutral phrasing or removes the
 * fragment. Conservative: only matches whole-word references with
 * appropriate articles to avoid mangling legitimate uses elsewhere.
 */
export function stripMetaPlatformTerms(input: string): string {
  if (typeof input !== 'string' || input.length === 0) return input;
  let out = input;

  // "the bóveda" / "the boveda" / "the Bóveda" referring to the platform.
  out = out.replace(/\bthe\s+b[oó]veda\b/gi, 'the world');
  // "Bóveda" as a place-name (capitalised).
  out = out.replace(/\bB[oó]veda\b/g, 'this place');
  // "the cube" referring to the worldbuilding container.
  out = out.replace(/\bthe\s+cube\b/gi, 'this world');
  // "the system" / "this system" (vague meta self-reference).
  out = out.replace(/\b(?:the|this)\s+system\b/gi, 'the world');
  // "the threshold" as platform metaphor (kept when used naturally
  // inside a sentence about an actual threshold; this only catches
  // the meta usage where it stands alone as a place-name).
  out = out.replace(/\b(?:in|at|on|to|from|inside|outside)\s+the\s+threshold\b/gi, (m) =>
    m.replace(/the\s+threshold/i, 'the edge')
  );
  // "the altar" when used as platform metaphor (specifically "the
  // bóveda altar" or similar). Standalone "altar" stays valid.
  out = out.replace(/\bthe\s+b[oó]veda\s+altar\b/gi, 'the altar');

  // Collapse double spaces left by replacements.
  out = out.replace(/\s{2,}/g, ' ');

  return out;
}

/**
 * Apply both em-dash and meta-platform strips. Single entry point
 * for any text generated by the LLM that should ship clean.
 */
export function cleanGeneratedText(input: string): string {
  return stripMetaPlatformTerms(stripEmDashes(input));
}

export function stripEmDashesInArray(input: string[]): string[] {
  return input.map((s) => stripEmDashes(s));
}
